plugins:
  zoom_enabled:
    default: false
    client: true
  zoom_api_key:
    default: ""
    client: false
  zoom_api_secret:
    default: ""
    client: false
  zoom_verification_token:
    default: ""
    client: true
  zoom_host_title_override:
    default: ""
    client: false
  zoom_send_user_id:
    default: false
