plugins:
  zoom_enabled:
    default: false
    client: true
  zoom_api_key:
    default: ""
    client: false
    secret: true
  zoom_api_secret:
    default: ""
    client: false
    secret: true
  zoom_verification_token:
    default: ""
    client: true
    secret: true
  zoom_host_title_override:
    default: ""
    client: false
  zoom_send_user_id:
    default: false
  zoom_send_reminder_minutes_before_webinar:
    default: 0
  zoom_display_attendees:
    default: false
    client: true
  zoom_join_x_mins_before_start:
    default: 0
    client: true
  zoom_enable_sdk_fallback:
    default: true
    client: true
